stages:

  data_ingestion:
    cmd: python src/KidneyTumorClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/KidneyTumorClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image-current


  prepare_base_model:
    cmd: python src/KidneyTumorClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
    - src/KidneyTumorClassifier/pipeline/stage_02_prepare_base_model.py
    - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/KidneyTumorClassifier/pipeline/stage_03_model_training.py
    deps:
      - src/KidneyTumorClassifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image-current
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5



  evaluation:
    cmd: python src/KidneyTumorClassifier/pipeline/stage_04_model_evaluation_with_mlflow.py
    deps:
      - src/KidneyTumorClassifier/pipeline/stage_04_model_evaluation_with_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image-current
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    metrics:
    - scores.json:
        cache: false


